config/routes.rb
Rails.application.routes.draw do
  # Priority: first created -> highest priority
  # Show all routes: "rake routes"

  root 'welcome#index'
  get 'about' => 'welcome#about'

  scope 'admin' do
    resources :members do
      get 'moi_sheet', on: :collection
      resources :memberships, only: [:index, :create, :destroy]
    end
  end

  devise_for :users

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title= @page_title || I18n.t("nehsaa")
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-default(role="navigation")
      .container-fluid
        .navbar-header
          button.navbar-toggle(type="button" data-toggle="collapse" data-target="#nehsaa-navigation-bar")
            span.sr-only Toggle Navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand(href="#{ root_path }") NEHSAA
        .collapse.navbar-collapse#nehsaa-navigation-bar
          ul.nav.navbar-nav
            li= link_to I18n.t("ui.about"), about_path
            li= link_to I18n.t("ui.member_management"), members_path
          ul.nav.navbar-nav.navbar-right
            li
              - if user_signed_in?
                = link_to I18n.t("ui.logout"), destroy_user_session_path, method: :delete
              - else
                = link_to I18n.t("ui.login"), new_user_session_path
    .container
      .row
        == breadcrumbs style: :bootstrap
      - if notice
        .row
          .alert.alert-info(role="alert")= notice
      - if alert
        .row
          .alert.alert-danger(role="alert")= alert
    = yield