config/routes.rb
Rails.application.routes.draw do
  # Priority: first created -> highest priority
  # Show all routes: "rake routes"

  root 'welcome#index'
  get 'about' => 'welcome#about'

  scope 'admin' do
    resources :members do
      get 'moi_sheet', on: :collection
      resources :memberships, only: [:index, :create, :destroy]
    end
  end

  devise_for :users

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/member.rb
class Member < ActiveRecord::Base
  extend TranslatedEnums

  enum gender: { male: 1, female: 2, other: 3 }

  enum member_type: {
    normal_member: 1,
    staff_member: 2,
    honor_member: 3
  }

  enum grad_department: {
    kindergarten: 1,
    elementary: 2,
    junior_high: 3,
    senior_high: 4,
    bilingual: 5
  }

  validates :name, :security_id,
            :birthdate, :gender, :member_type,
            :email, :phone, :address,
            :occupation, :company, :education,
            { presence: true }
  validates :security_id,     security_id: true, uniqueness: true
  validates :permanent,       inclusion: { in: [true, false] }
  validates :email,           email: true

  has_many :memberships, dependent: :delete_all

  def age(date = Date.today)
    date.year - birthdate.year
  end

  def membership?(date = Date.today)
    flag = memberships.count > 0
    if flag
      flag = memberships.order(year: :asc).last.year >= (date.year - 2)
    end
    valid? && (age(date) < 20 || flag || permanent)
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!

  def index
    @members = Member.all.includes(:memberships)
    @member_grid = initialize_grid(@members)
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.create(member_params)
    if @member.valid?
      redirect_to @member
    else
      render action: 'new'
    end
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.update(params[:id], member_params)
    if @member.valid?
      redirect_to @member
    else
      render action: 'edit'
    end
  end

  def destroy
    Member.destroy(params[:id])
    redirect_to action: 'index'
  end

  def moi_sheet
    @members = Member.all
    #response.headers['Content-Type'] = 'text/html; charset=UTF-8'
    #response.headers['Content-Disposition'] = 'attachment; filename="moi-sheet.html"'
    render layout: false, stream: true
  end

  private

  def allowed_attributes
    %i(name security_id birthdate gender
       member_type permanent
       email phone address occupation company education facebook
       grad_class grad_year grad_id grad_department)
  end

  def member_params
    unless @member_params
      @member_params = params.require(:member)
      @member_params = @member_params.permit(*allowed_attributes)
    end
    @member_params
  end

end

app/views/members/_form.html.slim
= simple_form_for @member do |f|
  = f.input :name
  = f.input :security_id
  = f.input :gender
  = f.input :birthdate, start_year: 1900, end_year: Date.today.year
  = f.input :member_type
  = f.input :permanent
  = f.input :email
  = f.input :phone
  = f.input :address
  = f.input :occupation
  = f.input :company
  = f.input :education
  = f.input :facebook
  = f.input :grad_class
  = f.input :grad_department
  = f.input :grad_year
  = f.input :grad_id
  = f.button :submit

app/views/members/edit.html.slim
- breadcrumb :edit_member, @member
.container
  .row
    = render "form"

app/views/members/index.html.slim
- breadcrumb :members
.container
  .row
    .panel.panel-default
      .panel-body
        = link_to new_member_path, class: 'btn btn-default' do
          = I18n.t("ui.new_member")
          span.glyphicon.glyphicon-plus
        = link_to({controller: :members, action: :moi_sheet}, {class: "btn btn-default", role: 'button', target: '_blank'}) do
          = I18n.t('ui.get_moi_sheet')
          span.glyphicon.glyphicon-list-alt
  .row
    == grid(@member_grid, show_filters: :always) do |g|
      - g.column(name: 'ID', attribute: 'id', filter: false) do |m|
        - link_to(m.id, member_path(m))
      - g.column(name: Member.human_attribute_name('name'), attribute: 'name') do |m|
        - link_to(m.name, member_path(m))
      - g.column(name: Member.human_attribute_name('gender'), attribute: 'gender', filter: false) do |m|
        - m.gender_tr
      - g.column(name: Member.human_attribute_name('birthdate'), attribute: 'birthdate', filter: false)  do |m|
        - I18n.l m.birthdate, format: :long
      - g.column(name: Member.human_attribute_name('security_id'), attribute: 'security_id')
      - g.column(name: Member.human_attribute_name('member_type'), attribute: 'member_type', filter: false) do |m|
        - m.member_type_tr
      - g.column(name: Member.human_attribute_name('membership?')) do |m|
        - I18n.t(m.membership? ? 'yes' : 'no')
      - g.column(name: Member.human_attribute_name('valid?')) do |m|
        - I18n.t(m.valid? ? 'yes' : 'no')
      - g.column do |m|
        - link_to(edit_member_path(m)) do
          span.glyphicon.glyphicon-pencil
          span= I18n.t("ui.edit")

app/views/members/moi_sheet.html.slim
doctype html
html
  head
    title= I18n.t("nehsaa")
    meta(charset="UTF-8")
  body
    table
      thead
        tr
          th= Member.human_attribute_name('name')
          th= Member.human_attribute_name('gender')
          th= Member.human_attribute_name('birthdate')
          th= Member.human_attribute_name('education')
          th= Member.human_attribute_name('occupation')
          th= Member.human_attribute_name('address')
          th= Member.human_attribute_name('phone')
          th= Member.human_attribute_name('comments')
      tbody
        - @members.find_each.select(&:membership?).each do |m|
          tr
            td= m.name
            td= m.gender_tr
            td= I18n.l m.birthdate, format: :long
            td= m.education
            td= m.occupation
            td= m.address
            td= m.phone
            td

app/views/members/new.html.slim
- breadcrumb :new_member
.container
  .row
    = render "form"

app/views/members/show.html.slim
- breadcrumb :member, @member
.container
  .row
    .panel.panel-default
      .panel-body
        = link_to edit_member_path(@member), class: 'btn btn-primary' do
          = I18n.t("ui.edit")
          span.glyphicon.glyphicon-pencil
        = link_to member_memberships_path(@member), class: 'btn btn-default' do
            = Membership.model_name.human
            span.glyphicon.glyphicon-list-alt
        = link_to member_path(@member), class: 'btn btn-danger pull-right', method: :delete, data: {confirm: I18n.t("ui.confirm_delete")} do
          = I18n.t("ui.delete")
          span.glyphicon.glyphicon-trash
  .row
    .col-md-6.bg-info
      h1.text-center= I18n.t "ui.basic_info"
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'name'
        .col-xs-8
          p= @member.name
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'gender'
        .col-xs-8
          p= @member.gender_tr
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'birthdate'
        .col-xs-8
          p= I18n.l @member.birthdate, format: :long
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'security_id'
        .col-xs-8
          p= @member.security_id
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'education'
        .col-xs-8
          p= @member.education
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'occupation'
        .col-xs-8
          p= @member.occupation
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'company'
        .col-xs-8
          p= @member.company
    .col-md-6.bg-success
      h2.text-center= I18n.t "ui.contact_info"
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'email'
        .col-xs-8
          p= @member.email
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'phone'
        .col-xs-8
          p= @member.phone
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'address'
        .col-xs-8
          p= @member.address
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'facebook'
        .col-xs-8
          p= @member.facebook
  .row
    .col-md-6
      h2.text-center= I18n.t "ui.graduation_info"
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'grad_class'
        .col-xs-8
          p= @member.grad_class
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'grad_year'
        .col-xs-8
          p= @member.grad_year
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'grad_id'
        .col-xs-8
          p= @member.grad_id
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'grad_department'
        .col-xs-8
          p= @member.grad_department_tr
    .col-md-6.bg-warning
      h2.text-center= I18n.t "ui.membership_status"
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'member_type'
        .col-xs-8
          p= @member.member_type_tr
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'permanent'
        .col-xs-8
          p= I18n.t(@member.permanent ? 'yes' : 'no')
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'membership?'
        .col-xs-8
          p= I18n.t(@member.membership? ? 'yes' : 'no')
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'valid?'
        .col-xs-8
          p= I18n.t(@member.valid? ? 'yes' : 'no')
      .row
        .col-xs-4
          p.text-right= Membership.model_name.human
        .col-xs-6
          = link_to member_memberships_path(@member) do
            = I18n.t("ui.list")
            span.glyphicon.glyphicon-list-alt